openapi: 3.0.0
info:
  title: TodoApi
  description: A simple to-do list
  version: 1.0.0
servers:
  - url: https://1638-2601-204-e782-f580-918a-534a-7410-67b3.ngrok-free.app/
    description: The todo api server
paths:
  /api/TodoItems:
    get:
      operationId: TodoItems
      summary: Returns a list of to-do items
      description: Returns a list of to-do items
      parameters:
        - name: searchParam
          in: query
          description: To do item name to search for
          schema:
            type: string
          required: false
      responses:
        '200':
          description: A list of to do items
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      description: The unique identifier of the to-do item
                    name:
                      type: string
                      description: The name of the to-do item
                    isComplete:
                      type: boolean
                      description: The status of the to-do item
